### ISSUE TITLE
Correct smbios

### ISSUE THREAD

**Issue by Siarhei-Ketsko** [m4ary/OpenCore-Asus-Prime-Z390A_i7-9700K_RX580#1]
Hi, you can find out why in config.plist smbios imac18.1, because I looked at Dortania and there | Coffee Lake (S) | iMac19.1 | iMac19.2. Which one is better to choose?

**Comment by m4ary** [comment]
hello 

i try the iMac19.1 but i didn't work for me , i think because my setup used to be clover then i upgrade it to opencore
