### ISSUE TITLE
Any chance of updating this for Monterey ?

### ISSUE THREAD

**Issue by Installer0001** [m4ary/OpenCore-Asus-Prime-Z390A_i7-9700K_RX580#2]
Hi, I have been using your opencore and it works flawless. I have everything same as you but I didn't have any knowledge of opencore. Luckily I found your repo and was able to get Big Sur but however I couldn't update to Monterey. Would you be able to update to latest opencore? Thank you in advance.

**Comment by m4ary** [comment]
Hello
Actually I have it working on beta but I will updated it this week for the release version

**Comment by Installer0001** [comment]
Thanks a lot, I tried to update opencore to latest and updated the kexts... then it doesn't boot anymore!

**Comment by m4ary** [comment]
you can try the new release new , i updated it.

don't forget to use your current S\N

**Comment by Installer0001** [comment]
Hey thank you so much, i have updated myself to 0.7.4 but I'll use yours to update to 0.7.5

Great work again! Appreciate that you took time for me.
