### ISSUE TITLE
Would you be willing to update this to MacOS Sonoma? 

### ISSUE THREAD

**Issue by stryk3rr3al** [m4ary/OpenCore-Asus-Prime-Z390A_i7-9700K_RX580#5]
This installation was the easiest Hackintosh installation I've ever done, so thank you for that! 
I'm just curious if you have plans to update this for Sonoma?

**Comment by m4ary** [comment]
Thanks for your kind words! 

Unfortunately, Apple doesn't support iMac18,1 on Sonoma, so I have to use OpenCore Legacy Patcher but There are a few issues like Bluetooth, T1 Security chip, USB 1.1, and graphics problems. 

Updating isn't worth the hassle, but you can check out the details [here](https://dortania.github.io/OpenCore-Legacy-Patcher/SONOMA-DROP.html#versioning). 

feel free to fork and pull request later.
